
services:
  app:
    build:
      context: .
    container_name: football-match-app
    restart: unless-stopped
    depends_on:
      - db
      - db_test
  db:
    image: mariadb:10.6
    container_name: football-match-mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: football_match
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: football_match
      MYSQL_PASSWORD: password
    ports:
      - "3106:3306"
    volumes:
      - dbdata:/var/lib/mysql

  db_test:
    image: mariadb:10.6
    container_name: football-match-mariadb-test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: football_match
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: football_match
      MYSQL_PASSWORD: password

  web:
    image: nginx:alpine
    container_name: football-match-nginx
    restart: unless-stopped
    ports:
      - "9090:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata: